### PR TITLE
provide server address via conf or cli

### PR DESCRIPTION
**Pull request by gilv**
Currently the way to provide server IP is by manually edit skyproxy.rs and skystore_cli.py and re build the code.

This PR leaves the existing approach as, but also add an option to provide server IP via CLI

`skystore init --config myconf --server_addr=<IP address or localhost>`

or via conf file, as example

     {
      "init_regions": [
        "aws:eu-central-1"
       ],
      "client_from_region": "aws:eu-central-1",
      "skystore_bucket_prefix": "skystore",
      "policy": "write_local",
      "server_addr": "IP of the SkyStore Server"
     }

### CODE REVIEW

**Review by lynnliu030 — APPROVED** [review]
LGTM!

**Comment by gilv** [comment]
@lynnliu030 what commands should I run to pass checks? sorry, didn't found anything in the documentation

**Comment by lynnliu030** [comment]
@gilv The checks are in this workflow: https://github.com/skyplane-project/skystore/tree/main/.github/workflows. For rust this is `cargo fmt --check && cargo clippy -- -D warnings` and for python `black --check .; ruff check .`

**Comment by gilv** [comment]
@lynnliu030 Python checks fails on the code that has nothing to do to my PR.  And if I run black --check .; ruff check  on my laptop, all is formatted correctly.

      Successfully installed black-24.1.1 mypy-extensions-1.0.0 pathspec-0.12.1 platformdirs-4.2.0 ruff-0.2.1
      would reformat /home/runner/work/skystore/skystore/store-server/operations/policy/utils/helper.py
      would reformat /home/runner/work/skystore/skystore/store-server/operations/object_operations.py

     Oh no! 💥 💔 💥
     2 files would be reformatted, 12 files would be left unchanged.
     Error: Process completed with exit code 1.

**Comment by lynnliu030** [comment]
@gilv Idk what happens but the current main branch has no checking failures. Maybe you can try reformatting it again? Currently the python test still fails

**Comment by gilv** [comment]
@lynnliu030 can you please merge it?

**Pull request merged**
