### PR TITLE
Skystore bucket fix

### PR DESCRIPTION
**Pull request by gilv**
Few fixes and additions:

1. support for head bucket to see if bucket already exists
2. previous code has a bug where SkyStore bucket had a name skystore-<region_name>. This is wrong, since buckets in AWS are unique per all users. I fixed the issue by using skystore-<user name>-<region_name>

### CODE REVIEW

**Comment by lynnliu030** [comment]
@gilv you can try re-running `cd s3-proxy && cargo fmt --check && cargo clippy -- -D warnings` locally, i think it's just formatting error

**Comment by gilv** [comment]
@lynnliu030 there is now 100% backward comparability. There is an option to add 
`"skystore_bucket_prefix" : "<bucket prefix>"` to the config files. If nothing added, the default is `skystore`

**Comment by lynnliu030** [comment]
@gilv Can you also fix the error in unit test? Thanks!

**Comment by gilv** [comment]
@lynnliu030 how to check formatting of Python code? it fails on some formatting issues

**Comment by gilv** [comment]
@lynnliu030 I think this is ready. No more issues I aware of

**Comment by gilv** [comment]
@lynnliu030 can you merge it please? otherwise I need to update this branch all the time, and it's not possible to work with master branch since it use "skystore-<region>" for all accounts and it fails in AWS since bucket name is unique per all accounts

**Pull request merged**
